(()=>{
'use strict';
const M=window.MF;if(!M)return;const {$,state,save,norm,esc}=M;
const STORE='mf_aiRecipes';
function loadSaved(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function persist(list){localStorage.setItem(STORE,JSON.stringify(list))}
function validRecipe(r){return r&&typeof r.name==='string'&&['Desayuno','Almuerzo','Cena'].includes(r.type)&&Array.isArray(r.ingredients)&&r.ingredients.length&&typeof r.steps==='string'}
function normalizeRecipe(r){return{...r,id:r.id||`AI-${Date.now()}`,day:0,week:0,origin:'IA generativa',sourceType:'ia',components:r.components||'',protein:r.protein||'',carb:r.carb||'',produce:r.produce||'',time:Number(r.time)||null,childNote:r.childNote||'Adaptar textura y porción a la edad del niño.',ingredients:r.ingredients.map(i=>({name:i.name||String(i),qty:i.qty??null,unit:i.unit||'',category:i.category||'Otros'}))}}
const saved=loadSaved().filter(validRecipe).map(normalizeRecipe);saved.forEach(r=>{if(!M.D.recipes.some(x=>x.id===r.id))M.D.recipes.push(r)});
async function generate(prompt){if(!state.aiEndpoint)throw new Error('Primero configura un endpoint seguro de IA en Ajustes.');const profile=M.familyProfile?.()||{},payload={task:'generate_recipe',prompt,context:{country:'Colombia',familyProfile:profile,pantry:Object.values(state.pantry||{}),rules:{healthyPlate:true,maxMajorCarbs:2,childFriendly:true}}};const res=await fetch(state.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error(`El backend respondió ${res.status}.`);const data=await res.json(),raw=data.recipe||data;if(!validRecipe(raw))throw new Error('La respuesta no cumple el formato esperado de receta.');const recipe=normalizeRecipe(raw),all=loadSaved();all.push(recipe);persist(all);M.D.recipes.push(recipe);return recipe}
const originalPantry=M.renderers.pantry;
M.renderers.pantry=()=>{originalPantry?.();const root=$('#pantry');if(!root)return;root.insertAdjacentHTML('beforeend',`<section class="card ai-lab"><h2>✨ Generador con IA</h2><p class="sub">Preparado para funcionar con un backend seguro. Sin endpoint configurado, la app continúa usando todos los motores locales.</p><textarea id="aiPrompt" class="search textarea" rows="3" placeholder="Ej.: tengo pollo, arroz, tomate y zanahoria; crea una cena para 3 personas en 30 minutos."></textarea><div class="button-row"><button class="btn primary" id="aiGenerate" ${state.aiEndpoint?'':'disabled'}>Generar receta nueva</button><span class="sub">${state.aiEndpoint?'Backend configurado':'Pendiente de backend seguro'}</span></div><div id="aiStatus" class="sub"></div></section>`);$('#aiGenerate')&&($('#aiGenerate').onclick=async()=>{const prompt=$('#aiPrompt').value.trim();if(!prompt)return;const btn=$('#aiGenerate');btn.disabled=true;$('#aiStatus').textContent='Generando…';try{const r=await generate(prompt);$('#aiStatus').innerHTML=`Receta guardada: <b>${esc(r.name)}</b>. Ya aparece en la biblioteca.`}catch(err){$('#aiStatus').textContent=err.message||'No se pudo generar.'}finally{btn.disabled=false}})};
const originalSettings=M.renderers.settings;
M.renderers.settings=()=>{originalSettings?.();const root=$('#settings');if(!root)return;const count=loadSaved().length;root.insertAdjacentHTML('beforeend',`<div class="card"><h3>🤖 Integración de IA</h3><p class="sub">Estado: ${state.aiEndpoint?'endpoint configurado':'sin backend configurado'}. Las claves nunca deben almacenarse en GitHub Pages ni en el navegador.</p><p class="sub">Recetas IA guardadas localmente: ${count}.</p>${count?'<button class="btn secondary" id="clearAiRecipes">Eliminar recetas IA locales</button>':''}</div>`);$('#clearAiRecipes')&&($('#clearAiRecipes').onclick=()=>{if(confirm('¿Eliminar las recetas generadas con IA guardadas en este dispositivo?')){localStorage.removeItem(STORE);location.reload()}})};
M.aiClient={generate};
})();
