(()=>{
'use strict';
const M=window.MF;if(!M)return;
const {state,save,norm,esc}=M,C=window.MF_COMPONENTS||{},original=M.renderers.pantry;
const proteinFamilies=['pollo','res','cerdo','pescado','atun','huevo','lenteja','frijol','garbanzo','arveja'];
const aliases={pollo:['pollo','pechuga','muslo'],res:['res','carne de res','bistec'],cerdo:['cerdo','lomo de cerdo'],pescado:['pescado','tilapia','trucha','salmon','salmón','camaron','camarón'],atun:['atun','atún'],huevo:['huevo','huevos'],lenteja:['lenteja','lentejas'],frijol:['frijol','fríjol','frijoles','fríjoles'],garbanzo:['garbanzo','garbanzos'],arveja:['arveja','arvejas'],arroz:['arroz'],papa:['papa'],yuca:['yuca'],platano:['platano','plátano'],arepa:['arepa'],quinua:['quinua','quinoa'],pasta:['pasta','fideo','soba','udon'],batata:['batata','camote'],maiz:['maiz','maíz','mazorca','polenta'],ensalada:['ensalada'],verdura:['verdura','vegetal'],brocoli:['brócoli','brocoli'],habichuela:['habichuela'],berenjena:['berenjena'],calabacin:['calabacín','calabacin']};
const canonCache=new Map();
function canonical(v){const n=norm(v);if(canonCache.has(n))return canonCache.get(n);let out=n;for(const [k,arr] of Object.entries(aliases)){if(arr.some(a=>n===norm(a)||n.includes(norm(a))||norm(a).includes(n))){out=k;break}}canonCache.set(n,out);return out}
function same(a,b){const na=norm(a),nb=norm(b);if(!na||!nb)return false;return na===nb||canonical(na)===canonical(nb)||na.includes(nb)||nb.includes(na)}
function pantry(){return Object.values(state.pantry||{})}
function ingredients(item){return [...new Set((item.ingredients||[]).map(String))]}
function estimate(item,type){if(item.time)return Number(item.time);const t=norm(`${item.name} ${(item.tags||[]).join(' ')}`);if(t.includes('horno')||t.includes('asada'))return type==='protein'?35:25;if(t.includes('guis'))return type==='protein'?35:25;if(t.includes('vapor'))return 18;if(t.includes('salte')||t.includes('wok'))return 15;if(t.includes('plancha'))return 20;if(type==='carb')return 20;if(type==='vegetable')return 15;if(type==='protein')return 25;return 10}
function makeCtx(){const rows=pantry();return{rows,count:rows.length,signature:rows.map(x=>`${norm(x.name)}:${x.qty||''}:${x.unit||''}`).sort().join('|')}}
function compScore(item,type,ctx){const req=ingredients(item),matched=req.filter(i=>ctx.rows.some(x=>same(x.name,i))),missing=req.filter(i=>!ctx.rows.some(x=>same(x.name,i))),coverage=req.length?matched.length/req.length:0,uses=ctx.rows.filter(x=>req.some(i=>same(x.name,i))).length;return{item,type,req,matched,missing,coverage,uses,time:estimate(item,type)}}
function top(group,type,n,ctx){return(group||[]).map(x=>compScore(x,type,ctx)).sort((a,b)=>b.uses-a.uses||a.missing.length-b.missing.length||b.coverage-a.coverage||a.time-b.time).slice(0,n)}
function uniq(arr){const out=[];for(const x of arr)if(!out.some(y=>same(y,x)))out.push(x);return out}
function plateData(p,v,c,ctx){const req=uniq([...p.req,...v.req,...c.req]),matched=req.filter(i=>ctx.rows.some(x=>same(x.name,i))),missing=req.filter(i=>!ctx.rows.some(x=>same(x.name,i))),uses=ctx.rows.filter(x=>req.some(i=>same(x.name,i))).length,coverage=req.length?matched.length/req.length:0,time=Math.max(p.time,v.time,c.time)+8;return{p,v,c,req,matched,missing,uses,coverage,time,key:`${p.item.id}|${v.item.id}|${c.item.id}`}}
let cache={sig:'',picks:[],sauces:[],soups:[]};
function rankedPlates(ctx){if(cache.sig===ctx.signature)return cache.picks;let ps=top(C.proteins,'protein',6,ctx),vs=top([...(C.salads||[]),...(C.cookedVegetables||[])],'vegetable',8,ctx),cs=top(C.carbs,'carb',6,ctx);const selected=new Set(ctx.rows.map(x=>canonical(x.name)).filter(x=>proteinFamilies.includes(x)));if(selected.size){const filtered=ps.filter(x=>[x.item.name,...x.req,...(x.item.tags||[])].some(n=>selected.has(canonical(n))));if(filtered.length)ps=filtered}const all=[];for(const p of ps)for(const v of vs)for(const c of cs)all.push(plateData(p,v,c,ctx));const best=[...all].sort((a,b)=>(b.uses*14-b.missing.length*9+b.coverage*45-b.time*.15)-(a.uses*14-a.missing.length*9+a.coverage*45-a.time*.15))[0];const fastest=[...all].filter(x=>x.uses>0&&x.missing.length<=Math.max(4,(best?.missing.length||0)+2)).sort((a,b)=>a.time-b.time||a.missing.length-b.missing.length||b.uses-a.uses)[0];const fewest=[...all].sort((a,b)=>a.missing.length-b.missing.length||b.uses-a.uses||b.coverage-a.coverage||a.time-b.time)[0];const picks=[['Mejor con tu despensa',best,'🥇'],['Más rápido',fastest,'⚡'],['Menos compras',fewest,'🛒']].filter(x=>x[1]),seen=new Set(),unique=picks.filter(x=>{if(seen.has(x[1].key))return false;seen.add(x[1].key);return true});cache={sig:ctx.signature,picks:unique,sauces:[],soups:[]};return unique}
function optionalList(group,type,limit,pairFamilies,ctx){return(group||[]).map(x=>{const s=compScore(x,type,ctx),pairs=(x.pairs||[]).map(canonical),bonus=pairFamilies.some(f=>pairs.includes(canonical(f)))?3:0;return{...s,pairBonus:bonus}}).sort((a,b)=>b.pairBonus-a.pairBonus||b.uses-a.uses||a.missing.length-b.missing.length||b.coverage-a.coverage||a.time-b.time).slice(0,limit)}
function plateCard(label,x,icon,idx){const vegType=(C.salads||[]).some(v=>v.id===x.v.item.id)?'Ensalada':'Verdura cocida';return `<article class="auto-plate"><div class="auto-head"><span class="auto-icon">${icon}</span><div><b>${esc(label)}</b><div class="sub">${x.uses} ingredientes de tu despensa · ${x.missing.length?`${x.missing.length} faltantes`:'sin compras adicionales'} · ~${x.time} min</div></div></div><div class="auto-grid"><div><span>Proteína</span><b>${esc(x.p.item.name)}</b></div><div><span>${vegType}</span><b>${esc(x.v.item.name)}</b></div><div><span>Carbohidrato</span><b>${esc(x.c.item.name)}</b></div></div>${x.missing.length?`<div class="sub auto-missing"><b>Faltaría:</b> ${x.missing.map(esc).join(', ')}</div>`:'<div class="intent-ok">Tienes todos los ingredientes base.</div>'}<div class="auto-actions">${x.missing.length?`<button class="btn small secondary" data-auto-shop="${idx}">Añadir faltantes a compras</button>`:''}</div></article>`}
function miniCard(x,kind){const extra=kind==='sauce'?(x.item.uses?.length?`<div class="usage-note"><b>Úsalo con:</b> ${x.item.uses.slice(0,5).map(esc).join(', ')}.</div>`:''):`<div class="usage-note"><b>${esc(x.item.mealRole||'Sopa')}:</b> ${esc(x.item.note||'')}</div>`;return `<article class="mini-option"><b>${esc(x.item.name)}</b><div class="sub">${x.uses} ingredientes disponibles · ${x.missing.length?`faltan ${x.missing.length}`:'lista para preparar'} · ~${x.time} min</div>${extra}<div class="component-ings">${x.req.map(i=>`<span class="mini-chip ${x.matched.some(m=>same(m,i))?'have':'need'}">${esc(i)}</span>`).join('')}</div></article>`}
function catalogCard(item,kind){const uses=kind==='sauce'?`<div class="catalog-uses"><b>Ideal para:</b> ${(item.uses||[]).map(esc).join(', ')}</div>`:`<div class="catalog-uses"><b>${esc(item.mealRole||'Sopa')}:</b> ${esc(item.note||'')}</div>`;return `<article class="catalog-item"><div class="catalog-title"><b>${esc(item.name)}</b><span>~${item.time||'—'} min</span></div>${uses}<div class="sub">Ingredientes: ${(item.ingredients||[]).map(esc).join(', ')}</div>${item.prep?`<div class="sub"><b>Preparación:</b> ${esc(item.prep)}</div>`:''}</article>`}
let lastPlates=[];
function shell(){const root=document.querySelector('#pantry');if(!root||root.querySelector('.auto-builder'))return;root.insertAdjacentHTML('beforeend',`<section class="auto-builder card"><div class="section-title"><div><h2>🧠 Constructor automático</h2><p>Combina proteína, vegetal y carbohidrato usando primero lo que ya tienes. Se calcula solo cuando abres “Qué cocinar”.</p></div></div><div id="autoBuilderBody" class="empty compact-empty">Abre <b>Qué cocinar</b> para generar propuestas.</div><div class="auto-catalog-actions" style="margin-top:12px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn small secondary" data-load-catalog="soups">Ver ${C.soups?.length||0} sopas y cremas</button><button class="btn small secondary" data-load-catalog="sauces">Ver ${C.sauces?.length||0} salsas y aderezos</button></div><div id="autoCatalog"></div></section>`);root.querySelectorAll('[data-load-catalog]').forEach(b=>b.onclick=()=>loadCatalog(b.dataset.loadCatalog))}
function hydrate(){const body=document.querySelector('#autoBuilderBody');if(!body)return;const ctx=makeCtx();if(!ctx.count){body.innerHTML='<div class="empty compact-empty">Registra algunos ingredientes para generar propuestas automáticas.</div>';return}body.innerHTML='<div class="empty compact-empty">Construyendo propuestas…</div>';requestAnimationFrame(()=>setTimeout(()=>{if(!document.body.contains(body))return;const picks=rankedPlates(ctx);lastPlates=picks.map(x=>x[1]);const best=picks[0]?.[1],pairFamilies=best?[canonical(best.p.item.name),canonical(best.c.item.name)]:[],sauces=optionalList(C.sauces,'sauce',3,pairFamilies,ctx),soups=optionalList(C.soups,'soup',3,[],ctx);body.innerHTML=`<div class="auto-plates">${picks.map((x,i)=>plateCard(x[0],x[1],x[2],i)).join('')}</div><div class="optional-grid"><div><h3>🥣 Sopas y cremas sugeridas</h3>${soups.map(x=>miniCard(x,'soup')).join('')}</div><div><h3>🥗 Salsas y aderezos sugeridos</h3>${sauces.map(x=>miniCard(x,'sauce')).join('')}</div></div><div class="notice" style="margin-top:12px">Las sopas marcadas como <b>plato completo</b> pueden sustituir el plato principal. Evita duplicar papa, yuca, maíz, plátano o leguminosas innecesariamente.</div>`;body.querySelectorAll('[data-auto-shop]').forEach(b=>b.onclick=()=>{const x=lastPlates[Number(b.dataset.autoShop)];if(!x)return;x.missing.forEach(name=>{const k=norm(name);state.extraShopping[k]={ingredient:name,category:'Constructor automático',unit:'',qty:1}});save();b.textContent='Añadidos ✓';b.disabled=true})},0))}
function loadCatalog(kind){const box=document.querySelector('#autoCatalog');if(!box)return;const rows=kind==='soups'?(C.soups||[]):(C.sauces||[]),label=kind==='soups'?'sopas y cremas':'salsas y aderezos';box.innerHTML=`<details class="culinary-catalog" open><summary>Catálogo de ${rows.length} ${label}</summary><div class="catalog-grid">${rows.map(x=>catalogCard(x,kind==='soups'?'soup':'sauce')).join('')}</div></details>`}
function schedule(){if((localStorage.getItem('mf_pantryMode')||'ingredients')!=='ideas')return;requestAnimationFrame(()=>setTimeout(hydrate,0))}
M.renderers.pantry=()=>{original?.();shell();schedule()};
document.addEventListener('click',e=>{if(e.target.closest('[data-v9-pantry-mode="ideas"]'))requestAnimationFrame(()=>setTimeout(hydrate,0))});
})();