(()=>{
'use strict';
const M=window.MF;if(!M)return;const {$,state,save,esc}=M;
const KEY='mf_familyProfile';
const defaults={members:[{name:'Adulto 1',age:42},{name:'Adulto 2',age:38},{name:'Niño',age:4}],budget:'medio',weekdayTime:35,weekendTime:60,maxNewIngredients:12,dislikes:'',restrictions:'',country:'Colombia'};
function loadProfile(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
let profile=loadProfile();
function persist(){localStorage.setItem(KEY,JSON.stringify(profile))}
function memberRows(){return profile.members.map((m,i)=>`<div class="profile-member"><input class="field" data-member-name="${i}" value="${esc(m.name||'')}" placeholder="Nombre"><input class="field age-field" data-member-age="${i}" type="number" min="1" max="110" value="${Number(m.age)||''}" aria-label="Edad"><button class="btn small secondary" data-remove-member="${i}" ${profile.members.length<=1?'disabled':''}>Quitar</button></div>`).join('')}
function backup(){const data={app:'menu-familiar',version:1,exportedAt:new Date().toISOString(),storage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('mf_'))data.storage[k]=localStorage.getItem(k)};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`menu-familiar-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function restore(file){const txt=await file.text();const data=JSON.parse(txt);if(data?.app!=='menu-familiar'||!data.storage)throw new Error('El archivo no corresponde a Menú Familiar.');Object.entries(data.storage).forEach(([k,v])=>{if(k.startsWith('mf_')&&typeof v==='string')localStorage.setItem(k,v)});location.reload()}
const original=M.renderers.settings;
M.renderers.settings=()=>{original?.();const root=$('#settings');if(!root)return;root.insertAdjacentHTML('afterbegin',`<div class="card family-profile-card"><h3>👨‍👩‍👧 Perfil familiar</h3><p class="sub">Se usa para escalar cantidades y planificar. No sustituye una valoración nutricional individual.</p><div id="profileMembers">${memberRows()}</div><button class="btn small secondary" id="addMember">Añadir persona</button><div class="profile-grid"><label>Presupuesto<select class="field" id="profileBudget"><option value="economico" ${profile.budget==='economico'?'selected':''}>Económico</option><option value="medio" ${profile.budget==='medio'?'selected':''}>Medio</option><option value="amplio" ${profile.budget==='amplio'?'selected':''}>Amplio</option></select></label><label>Tiempo entre semana (min)<input class="field" id="weekdayTime" type="number" min="15" max="120" value="${Number(profile.weekdayTime)||35}"></label><label>Tiempo fin de semana (min)<input class="field" id="weekendTime" type="number" min="15" max="180" value="${Number(profile.weekendTime)||60}"></label><label>Máx. ingredientes nuevos/semana<input class="field" id="maxNewIngredients" type="number" min="3" max="40" value="${Number(profile.maxNewIngredients)||12}"></label></div><label>Alimentos que no gustan<input class="field" id="profileDislikes" placeholder="Ej.: berenjena, champiñón" value="${esc(profile.dislikes||'')}"></label><label>Restricciones o preferencias<input class="field" id="profileRestrictions" placeholder="Ej.: sin cerdo" value="${esc(profile.restrictions||'')}"></label></div><div class="card backup-card"><h3>💾 Copia y traslado de datos</h3><p class="sub">Mientras no exista sincronización en la nube, esta copia permite mover despensa, favoritos, compras, perfil y planes entre teléfonos.</p><div class="button-row"><button class="btn secondary" id="exportBackup">Exportar datos</button><label class="btn secondary file-btn">Importar datos<input id="importBackup" type="file" accept="application/json" hidden></label></div><div id="backupStatus" class="sub"></div></div>`);
 const rerender=()=>{persist();M.renderers.settings()};
 root.querySelectorAll('[data-member-name]').forEach(x=>x.onchange=()=>{profile.members[Number(x.dataset.memberName)].name=x.value.trim()||`Persona ${Number(x.dataset.memberName)+1}`;persist()});
 root.querySelectorAll('[data-member-age]').forEach(x=>x.onchange=()=>{profile.members[Number(x.dataset.memberAge)].age=Math.max(1,Number(x.value)||1);persist()});
 root.querySelectorAll('[data-remove-member]').forEach(x=>x.onclick=()=>{profile.members.splice(Number(x.dataset.removeMember),1);rerender()});
 $('#addMember').onclick=()=>{profile.members.push({name:`Persona ${profile.members.length+1}`,age:30});rerender()};
 $('#profileBudget').onchange=e=>{profile.budget=e.target.value;persist()};$('#weekdayTime').onchange=e=>{profile.weekdayTime=Number(e.target.value)||35;persist()};$('#weekendTime').onchange=e=>{profile.weekendTime=Number(e.target.value)||60;persist()};$('#maxNewIngredients').onchange=e=>{profile.maxNewIngredients=Number(e.target.value)||12;persist()};$('#profileDislikes').onchange=e=>{profile.dislikes=e.target.value.trim();persist()};$('#profileRestrictions').onchange=e=>{profile.restrictions=e.target.value.trim();persist()};
 $('#exportBackup').onclick=backup;$('#importBackup').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{await restore(f)}catch(err){$('#backupStatus').textContent=err.message||'No se pudo importar.'}};
 const reset=$('#resetBtn');if(reset)reset.onclick=()=>{if(confirm('¿Restablecer todos los datos locales de Menú Familiar?')){const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('mf_'))keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));location.reload()}};
};
M.familyProfile=()=>loadProfile();M.familyScale=()=>{const p=loadProfile(),equiv=(p.members||[]).reduce((a,m)=>a+(Number(m.age)<6?.5:Number(m.age)<12?.75:1),0);return Math.max(.4,equiv/2.5)};
})();
