(()=>{
'use strict';const M=window.MF,{D,$,$$,state,save,norm,esc,fmtQty}=M;
function key(x,i){return `${state.shopMode}|${x.week||0}|${norm(x.ingredient)}|${x.unit}|${i}`}
function extraKey(x){return `extra|${norm(x.ingredient)}`}
M.renderers.shopping=()=>{
 const rows=state.shopMode==='week'?D.weeklyShopping.filter(x=>x.week===state.shopWeek):D.monthlyShopping,groups={};
 rows.forEach(x=>(groups[x.category]??=[]).push(x));
 const cats=Object.keys(groups).sort((a,b)=>a.localeCompare(b,'es')),extras=Object.values(state.extraShopping||{}).sort((a,b)=>a.ingredient.localeCompare(b.ingredient,'es'));
 const total=rows.length+extras.length,donePlan=rows.filter((x,i)=>state.checked[key(x,i)]).length,doneExtra=extras.filter(x=>state.checked[extraKey(x)]).length,done=donePlan+doneExtra;
 $('#shopping').innerHTML=`<div class="section-title"><div><h2>Lista de compras</h2><p>La lista del plan se calcula solo con las 90 recetas programadas. Los faltantes elegidos desde la despensa aparecen aparte.</p></div></div><div class="shopping-head"><button class="chip ${state.shopMode==='week'?'active':''}" id="weekMode">Semana</button><button class="chip ${state.shopMode==='month'?'active':''}" id="monthMode">Mes</button>${state.shopMode==='week'?`<select id="weekSelect" class="field">${[1,2,3,4,5].map(w=>`<option value="${w}" ${state.shopWeek===w?'selected':''}>Semana ${w}</option>`).join('')}</select>`:''}<span class="grow"></span><button class="btn small secondary" id="uncheckAll">Desmarcar</button></div><div class="card"><div class="meta-row" style="justify-content:space-between"><b>Progreso</b><span>${done}/${total}</span></div><div class="progress" style="margin-top:8px"><span style="width:${total?Math.round(done/total*100):0}%"></span></div></div>${extras.length?`<div class="shopping-group"><div style="display:flex;align-items:center;gap:8px"><h3 style="margin-right:auto">Añadidos desde el constructor</h3><button class="btn small secondary" id="clearExtras">Vaciar adicionales</button></div>${extras.map(x=>{const k=extraKey(x),checked=!!state.checked[k];return `<div class="shop-item ${checked?'checked':''}" style="display:flex;align-items:center"><label style="display:flex;align-items:center;gap:10px;flex:1"><input type="checkbox" data-shop="${esc(k)}" ${checked?'checked':''}><span class="shop-name">${esc(x.ingredient)}</span></label><button class="favbtn" data-remove-extra="${esc(norm(x.ingredient))}" aria-label="Quitar ${esc(x.ingredient)}">×</button></div>`}).join('')}</div>`:''}${cats.map(cat=>`<div class="shopping-group"><h3>${esc(cat)}</h3>${groups[cat].map((x,i)=>{const k=key(x,i),checked=!!state.checked[k];return `<label class="shop-item ${checked?'checked':''}"><input type="checkbox" data-shop="${esc(k)}" ${checked?'checked':''}><span class="shop-name">${esc(x.ingredient)}</span><span class="shop-qty">${fmtQty(x.qty)} ${esc(x.unit)}</span></label>`}).join('')}</div>`).join('')}`;
 $('#weekMode').onclick=()=>{state.shopMode='week';M.renderers.shopping()};$('#monthMode').onclick=()=>{state.shopMode='month';M.renderers.shopping()};
 $('#weekSelect')&&($('#weekSelect').onchange=e=>{state.shopWeek=Number(e.target.value);save();M.renderers.shopping()});
 $('#uncheckAll').onclick=()=>{state.checked={};save();M.renderers.shopping()};
 $('#clearExtras')&&($('#clearExtras').onclick=()=>{state.extraShopping={};save();M.renderers.shopping()});
 $$('[data-remove-extra]').forEach(b=>b.onclick=()=>{delete state.extraShopping[b.dataset.removeExtra];delete state.checked[`extra|${b.dataset.removeExtra}`];save();M.renderers.shopping()});
 $$('[data-shop]').forEach(c=>c.onchange=()=>{state.checked[c.dataset.shop]=c.checked;save();M.renderers.shopping()})
};
})();
