(()=>{
'use strict';
const M=window.MF;if(!M)return;
const {D,$,$$,state,esc,norm}=M,C=window.MF_COMPONENTS||{};
let componentMode=localStorage.getItem('mf_v12ComponentMode')||'';
const modes={
 salads:{label:'Ensaladas',group:'salads',icon:'🥗',empty:'No encontré ensaladas con ese criterio.'},
 vegetables:{label:'Verduras y salteados',group:'cookedVegetables',icon:'🥦',empty:'No encontré preparaciones de verduras con ese criterio.'},
 sauces:{label:'Aderezos',group:'sauces',icon:'🥣',empty:'No encontré aderezos con ese criterio.'}
};
function text(x){return norm(`${x.name} ${(x.ingredients||[]).join(' ')} ${(x.tags||[]).join(' ')} ${x.method||''} ${(x.uses||[]).join(' ')}`)}
function steps(x){return Array.isArray(x.steps)&&x.steps.length?x.steps:['Prepara y mide los ingredientes.','Combina o cocina según la técnica indicada hasta alcanzar la textura deseada.','Prueba, ajusta la sazón y sirve de inmediato.']}
function componentCard(x,mode){const cfg=modes[mode],uses=x.uses?.length?`<div class="v12-uses"><b>Úsalo con:</b> ${x.uses.slice(0,7).map(esc).join(', ')}</div>`:'';return `<article class="recipe-card v12-component"><div class="v9-card-top"><span class="badge">${cfg.icon} ${esc(cfg.label)}</span><span class="origin-badge">${esc(x.method||'Preparación local')}</span></div><div class="title">${esc(x.name)}</div><div class="sub"><b>Ingredientes:</b> ${(x.ingredients||[]).map(esc).join(', ')}</div><div class="sub">⏱️ ${x.time||'—'} min${x.tags?.length?` · ${x.tags.slice(0,4).map(esc).join(' · ')}`:''}</div>${uses}<details class="v12-preparation"><summary>Cómo se prepara</summary><ol>${steps(x).map(s=>`<li>${esc(s)}</li>`).join('')}</ol></details></article>`}
function activeStandard(){return $('#recipes [data-v9-library].active')?.dataset?.v9Library||'Todos'}
function setTabVisual(mode){$('#recipes')?.querySelectorAll('[data-v9-library]').forEach(b=>b.classList.toggle('active',false));$('#recipes')?.querySelectorAll('[data-v12-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v12Mode===mode))}
function renderMode(mode=componentMode){const cfg=modes[mode];if(!cfg)return;componentMode=mode;localStorage.setItem('mf_v12ComponentMode',mode);const q=norm($('#recipeSearch')?.value||''),rows=(C[cfg.group]||[]).filter(x=>!q||text(x).includes(q)),root=$('#v9RecipeResults'),count=$('#v9RecipeCount');if(root)root.innerHTML=rows.length?rows.map(x=>componentCard(x,mode)).join(''):`<div class="empty">${cfg.empty}</div>`;if(count)count.textContent=`${rows.length} resultado${rows.length===1?'':'s'} · ${cfg.label}`;setTabVisual(mode)}
function renderDetailedSauces(){if(activeStandard()!=='Aderezos'||componentMode)return;const q=norm($('#recipeSearch')?.value||''),rows=(C.sauces||[]).filter(x=>!q||text(x).includes(q)),root=$('#v9RecipeResults'),count=$('#v9RecipeCount');if(root)root.innerHTML=rows.length?rows.map(x=>componentCard(x,'sauces')).join(''):'<div class="empty">No encontré aderezos.</div>';if(count)count.textContent=`${rows.length} resultado${rows.length===1?'':'s'} · Aderezos`}
function searchNow(){const input=$('#recipeSearch');if(!input)return;input.dispatchEvent(new Event('input',{bubbles:true}));if(componentMode)renderMode(componentMode);else if(activeStandard()==='Aderezos')renderDetailedSauces()}
function clearSearch(){const input=$('#recipeSearch');if(!input)return;input.value='';state.recipeQuery='';searchNow();input.focus()}
function enhance(){const root=$('#recipes');if(!root)return;const input=$('#recipeSearch'),wrap=root.querySelector('.v9-search-wrap');if(input&&wrap&&!root.querySelector('.v12-search-actions')){wrap.insertAdjacentHTML('afterend','<div class="v12-search-actions"><button class="btn primary" type="button" data-v12-search>Buscar</button><button class="btn secondary" type="button" data-v12-clear>Limpiar</button></div>');root.querySelector('[data-v12-search]').onclick=searchNow;root.querySelector('[data-v12-clear]').onclick=clearSearch;input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchNow()}});input.addEventListener('input',()=>{if(componentMode)requestAnimationFrame(()=>renderMode(componentMode));else if(activeStandard()==='Aderezos')requestAnimationFrame(renderDetailedSauces)})}
 const tabs=root.querySelector('.v9-library-tabs');if(tabs&&!root.querySelector('[data-v12-mode]')){tabs.insertAdjacentHTML('beforeend','<button class="chip" type="button" data-v12-mode="salads">Ensaladas</button><button class="chip" type="button" data-v12-mode="vegetables">Verduras y salteados</button>');root.querySelectorAll('[data-v12-mode]').forEach(b=>b.onclick=()=>{const exit=root.querySelector('[data-world-exit]:not([hidden])');if(exit){exit.click();requestAnimationFrame(()=>{componentMode=b.dataset.v12Mode;renderMode(componentMode)});return}renderMode(b.dataset.v12Mode)})}
 if(componentMode&&modes[componentMode])renderMode(componentMode);else if(activeStandard()==='Aderezos')renderDetailedSauces()}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-v9-library]');if(!b)return;componentMode='';localStorage.removeItem('mf_v12ComponentMode')},true);
const base=M.renderers.recipes;M.renderers.recipes=()=>{base?.();enhance()};
})();
