(()=>{
'use strict';
const M=window.MF;if(!M)return;
const {D,$,$$,state,norm,esc,mealIcon,favButton,bindFav,bindRecipeButtons}=M;
const C=window.MF_COMPONENTS||{};
let libraryTab=localStorage.getItem('mf_v9LibraryTab')||'Todos';
let pantryMode=localStorage.getItem('mf_pantryMode')||'ingredients';
let planMode=localStorage.getItem('mf_planMode')||(localStorage.getItem('mf_weekPlan')?'smart':'month');
let currentRecipeId='';

function recipeSearchText(r){return norm(`${r.name} ${r.type} ${r.protein||''} ${r.carb||''} ${r.produce||''} ${r.components||''} ${(r.ingredients||[]).map(i=>i.name).join(' ')} ${r.origin||''}`)}
function componentSearchText(x){return norm(`${x.name} ${(x.ingredients||[]).join(' ')} ${(x.tags||[]).join(' ')} ${(x.uses||[]).join(' ')} ${x.note||''}`)}
function recipeScope(r){return r.day>0?`Día ${r.day}`:'Biblioteca'}
function recipeSource(r){return r.origin||(r.day>0?'Plan mensual propio':'Biblioteca propia')}
function componentPrep(x,kind){
 const n=norm(`${x.name} ${(x.tags||[]).join(' ')}`);
 if(kind==='Aderezo'){
  if(n.includes('hogao')||n.includes('tomate')&&!n.includes('fresco'))return 'Pica finamente los ingredientes. Cocina primero cebolla y aromáticos a fuego medio; incorpora el tomate y cocina hasta obtener una salsa jugosa. Ajusta la textura con poca agua si hace falta y sirve tibio.';
  if(n.includes('asado'))return 'Asa o dora primero el ingrediente principal hasta que esté tierno. Deja entibiar, procesa o machaca con los demás ingredientes y ajusta la textura. Sirve en poca cantidad como complemento.';
  return 'Lava y prepara los ingredientes. Mezcla, bate o procesa hasta obtener una salsa homogénea; agrega el ácido al final y ajusta la consistencia poco a poco. Conserva refrigerado y sirve en porción moderada.';
 }
 const creamy=n.includes('crema');
 const legume=n.includes('lentej')||n.includes('frij')||n.includes('garban')||n.includes('arveja');
 let txt='Lava y corta los ingredientes en tamaños similares. Sofríe suavemente los aromáticos si la preparación los incluye, agrega los ingredientes principales y líquido suficiente para cubrir. Cocina hasta que estén tiernos.';
 if(legume)txt+=' Si usas leguminosa seca, asegúrate de que esté completamente cocida antes de continuar.';
 if(creamy)txt+=' Licúa o procesa con parte del líquido de cocción hasta lograr la textura deseada y vuelve a calentar suavemente.';
 else txt+=' Mantén parte de los vegetales enteros para conservar textura.';
 return txt+' Ajusta la sazón al final y sirve según su clasificación como entrada, sopa sustanciosa o plato completo.';
}
function componentCard(x,kind,q){const matches=!q||componentSearchText(x).includes(norm(q));if(!matches)return'';const uses=x.uses?.length?`<div class="sub"><b>Va bien con:</b> ${x.uses.slice(0,6).map(esc).join(', ')}</div>`:'';const note=x.note?`<div class="sub">${esc(x.note)}</div>`:'';return `<article class="recipe-card v9-component-card"><div class="v9-card-top"><span class="badge">${kind==='Sopa / crema'?'🥣':'🥗'} ${esc(kind)}</span><span class="grow"></span><span class="origin-badge">Catálogo local</span></div><div class="title">${esc(x.name)}</div><div class="sub">⏱️ ${x.time||'—'} min · ${(x.ingredients||[]).map(esc).join(', ')}</div>${uses}${note}<details class="v9-prep-mini"><summary>Ver preparación</summary><p>${esc(componentPrep(x,kind))}</p></details></article>`}
function recipeCard(r){return `<article class="recipe-card"><div class="v9-card-top"><span class="badge">${esc(recipeScope(r))} · ${mealIcon(r.type)} ${esc(r.type)}</span><span class="origin-badge">${esc(recipeSource(r))}</span><span class="grow"></span>${favButton(r)}</div><div class="title">${esc(r.name)}</div><div class="sub">${esc(r.components||`${r.protein||''} · ${r.carb||''}`)}</div><div class="foot"><span>⏱️ ${r.time||'—'} min</span><button class="btn small secondary" data-recipe="${esc(r.id)}">Ver receta</button></div></article>`}
function getLibraryResults(q=''){
 const nq=norm(q),ai=D.recipes.filter(r=>r.sourceType==='ia').length;
 if(libraryTab==='Sopas y cremas'){const rows=(C.soups||[]).filter(x=>!nq||componentSearchText(x).includes(nq));return{html:rows.map(x=>componentCard(x,'Sopa / crema',q)).join(''),count:rows.length,total:(C.soups||[]).length,summary:`${C.soups?.length||0} sopas y cremas`}}
 if(libraryTab==='Aderezos'){const rows=(C.sauces||[]).filter(x=>!nq||componentSearchText(x).includes(nq));return{html:rows.map(x=>componentCard(x,'Aderezo',q)).join(''),count:rows.length,total:(C.sauces||[]).length,summary:`${C.sauces?.length||0} salsas y aderezos`}}
 let rows=D.recipes.filter(r=>libraryTab==='Todos'||(libraryTab==='Favoritos'&&state.favorites[r.id])||r.type===libraryTab);
 if(nq)rows=rows.filter(r=>recipeSearchText(r).includes(nq));
 return{html:rows.map(recipeCard).join(''),count:rows.length,total:D.recipes.length,summary:`${D.recipes.length} recetas · 90 del plan mensual + ${Math.max(0,D.recipes.length-90-ai)} de biblioteca${ai?` + ${ai} IA`:''}`};
}
function updateLibraryResults(){const input=$('#recipeSearch'),q=input?.value||state.recipeQuery||'';state.recipeQuery=q;const data=getLibraryResults(q),count=$('#v9RecipeCount'),root=$('#v9RecipeResults');if(count)count.textContent=`${data.count} resultado${data.count===1?'':'s'}`;if(root){root.innerHTML=data.html||'<div class="empty">No encontré resultados. Prueba por ingrediente, nombre o tipo de preparación.</div>';bindRecipeButtons(root);bindFav(root)}}
M.renderers.recipes=()=>{const tabs=['Todos','Favoritos','Desayuno','Almuerzo','Cena','Sopas y cremas','Aderezos'],data=getLibraryResults(state.recipeQuery);$('#recipes').innerHTML=`<div class="section-title"><div><h2>Recetas y complementos</h2><p>${esc(data.summary)}. Busca por nombre, ingrediente o proteína.</p></div></div><div class="v9-search-wrap"><span aria-hidden="true">🔎</span><input id="recipeSearch" class="search" type="search" autocomplete="off" placeholder="Buscar pollo, lentejas, brócoli, yogur..." value="${esc(state.recipeQuery)}"><span id="v9RecipeCount" class="v9-result-count">${data.count} resultado${data.count===1?'':'s'}</span></div><div class="chips v9-library-tabs">${tabs.map(t=>`<button class="chip ${libraryTab===t?'active':''}" data-v9-library="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="recipe-list" id="v9RecipeResults">${data.html||'<div class="empty">No encontré resultados.</div>'}</div>`;$('#recipeSearch').oninput=e=>{state.recipeQuery=e.target.value;updateLibraryResults()};$$('[data-v9-library]').forEach(b=>b.onclick=()=>{libraryTab=b.dataset.v9Library;localStorage.setItem('mf_v9LibraryTab',libraryTab);state.recipeFilter=libraryTab;M.renderers.recipes()});bindRecipeButtons($('#v9RecipeResults'));bindFav($('#v9RecipeResults'))};

function detailNote(sentence){const n=norm(sentence);if(n.includes('saltear'))return 'Trabaja con sartén caliente y evita amontonar los ingredientes para que doren y conserven textura.';if(n.includes('hornear'))return 'Precalienta el horno, distribuye los alimentos en una sola capa y controla la cocción para evitar que se resequen.';if(n.includes('plancha')||n.includes('asar'))return 'Calienta bien la superficie antes de cocinar; evita mover la proteína constantemente y verifica que quede completamente cocida cuando corresponda.';if(n.includes('guis'))return 'Empieza por la base aromática, incorpora la proteína o leguminosa y cocina a fuego moderado hasta integrar sabores.';if(n.includes('arroz'))return 'Cocina el arroz en paralelo y déjalo reposar tapado unos minutos antes de soltarlo y servir.';if(n.includes('yuca')||n.includes('papa'))return 'Corta los tubérculos en tamaños parecidos y cocina hasta que estén tiernos sin deshacerse.';if(n.includes('ensalada'))return 'Lava y seca bien los vegetales; mezcla y adereza justo antes de servir para mantener textura.';if(n.includes('vapor'))return 'Cocina solo hasta que los vegetales estén tiernos pero mantengan color y algo de firmeza.';return ''}
function expandedPreparation(r){const base=String(r.steps||'').split(/[.;]+/).map(x=>x.trim()).filter(Boolean),ings=(r.ingredients||[]).map(i=>i.name),n=norm(`${r.name} ${r.protein} ${r.carb}`),rows=[];rows.push(`Organiza la mise en place: pesa o mide los ingredientes, lava y seca frutas y verduras, y corta los componentes antes de encender el fuego. Para esta receta prepara especialmente ${ings.slice(0,5).join(', ')}${ings.length>5?' y los demás ingredientes':''}.`);base.forEach(s=>{const note=detailNote(s);rows.push(`${s}.${note?` ${note}`:''}`)});if(/lentej|frij|garban|arveja/.test(n))rows.splice(1,0,'Si partes de leguminosa seca, revisa previamente el tiempo de remojo que corresponda y cocínala hasta que esté completamente tierna. Las lentejas normalmente requieren menos preparación previa que fríjoles o garbanzos.');if(/pollo/.test(n))rows.push('Comprueba que el pollo quede cocido completamente, sin zonas crudas en el centro. Déjalo reposar brevemente antes de cortarlo o servirlo.');else if(/pescado|tilapia|trucha|atun/.test(n))rows.push('Retira el pescado del calor cuando esté cocido y se separe con facilidad; evita prolongar la cocción para que no se reseque.');rows.push('Antes de servir, prueba la sazón y revisa el equilibrio del plato: una porción generosa de vegetales, la proteína prevista y el carbohidrato en la cantidad indicada. Sirve los componentes de forma separada para el niño si facilita su aceptación.');return rows}
function injectDetailedPrep(){if(!currentRecipeId)return;const r=D.recipes.find(x=>x.id===currentRecipeId),steps=$('#recipeModalBody .steps');if(!r||!steps||$('#recipeModalBody .v9-detailed-prep'))return;const rows=expandedPreparation(r);steps.insertAdjacentHTML('afterend',`<details class="v9-detailed-prep" open><summary>Preparación detallada · paso a paso</summary><ol>${rows.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details>`)}
const baseOpen=M.openRecipe;
if(baseOpen){M.openRecipe=id=>{currentRecipeId=id;baseOpen(id);setTimeout(injectDetailedPrep,0)};document.addEventListener('click',e=>{if(e.target.closest('#recipeModalBody [data-scale], #recipeModalBody [data-adapt]'))setTimeout(injectDetailedPrep,0)})}

function setPantryMode(mode){pantryMode=mode;localStorage.setItem('mf_pantryMode',mode);applyPantryMode()}
function applyPantryMode(){const root=$('#pantry');if(!root)return;root.querySelectorAll('[data-v9-pantry-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v9PantryMode===pantryMode));root.querySelectorAll('[data-v9-pane]').forEach(x=>x.hidden=x.dataset.v9Pane!==pantryMode)}
function enhancePantry(){const root=$('#pantry');if(!root||root.querySelector('.v9-pantry-switch'))return;const title=root.querySelector('.section-title');if(title){title.querySelector('h2')&&(title.querySelector('h2').textContent='Despensa y cocina');title.querySelector('p')&&(title.querySelector('p').textContent='Primero registra lo que tienes; después usa esos ingredientes para buscar o construir comidas.');title.insertAdjacentHTML('afterend',`<div class="v9-pantry-switch"><button class="chip ${pantryMode==='ingredients'?'active':''}" data-v9-pantry-mode="ingredients">🥕 Mis ingredientes</button><button class="chip ${pantryMode==='ideas'?'active':''}" data-v9-pantry-mode="ideas">✨ Qué cocinar</button></div>`)}
 const children=[...root.children].filter(x=>!x.classList.contains('section-title')&&!x.classList.contains('v9-pantry-switch'));
 let ideaStarted=false;
 children.forEach(el=>{const txt=norm(el.textContent);if(el.classList.contains('inventory-card')||txt.includes('que ingredientes tienes'))el.dataset.v9Pane='ingredients';else{if(txt.includes('que puedo cocinar')||txt.includes('recetas compatibles')||txt.includes('quiero cocinar con')||txt.includes('constructor'))ideaStarted=true;el.dataset.v9Pane=ideaStarted?'ideas':'ingredients'}});
 const entry=[...root.querySelectorAll('.card')].find(x=>norm(x.querySelector('h3')?.textContent).includes('que ingredientes tienes'));
 if(entry){const h=entry.querySelector('h3');if(h)h.textContent='Registrar ingredientes';const p=entry.querySelector('p.sub');if(p)p.innerHTML='Escribe una lista simple separada por comas o saltos de línea. Ejemplo: <b>pollo, arroz, tomate, brócoli</b>.';const a=entry.querySelector('#analyzePantry');if(a)a.textContent='Guardar ingredientes';const c=entry.querySelector('#clearPantry');if(c)c.textContent='Limpiar despensa'}
 const firstIdea=[...root.children].find(x=>x.dataset.v9Pane==='ideas');if(firstIdea&&!root.querySelector('#v9IdeaCard'))firstIdea.insertAdjacentHTML('beforebegin',`<div class="card v9-idea-card" id="v9IdeaCard" data-v9-pane="ideas"><h3>💬 Pedir una idea</h3><p class="sub">Puedes escribir una frase natural. La app extraerá ingredientes, tipo de comida y tiempo.</p><textarea id="v9IdeaInput" class="search" rows="3" placeholder="Tengo pollo, arroz y tomate. Quiero una cena de máximo 35 minutos."></textarea><button class="btn primary" id="v9IdeaAnalyze">Analizar idea</button></div>`);
 root.querySelectorAll('[data-v9-pantry-mode]').forEach(b=>b.onclick=()=>setPantryMode(b.dataset.v9PantryMode));const ideaBtn=$('#v9IdeaAnalyze');if(ideaBtn)ideaBtn.onclick=()=>{const source=$('#v9IdeaInput'),hiddenInput=$('#pantryInput'),analyze=$('#analyzePantry');if(!source?.value.trim())return;pantryMode='ideas';localStorage.setItem('mf_pantryMode','ideas');if(hiddenInput){hiddenInput.value=source.value;hiddenInput.dispatchEvent(new Event('input',{bubbles:true}))}analyze?.click()};applyPantryMode()}
const basePantry=M.renderers.pantry;M.renderers.pantry=()=>{basePantry?.();enhancePantry()};

function enhanceCalendar(){const root=$('#calendar');if(!root)return;const weekly=root.querySelector('.weekly-planner'),monthlyTitle=[...root.querySelectorAll(':scope > .section-title')][0],dayList=root.querySelector(':scope > .day-list');if(!weekly)return;if(!root.querySelector('.v9-plan-switch'))weekly.insertAdjacentHTML('beforebegin',`<div class="v9-plan-switch"><button class="chip ${planMode==='smart'?'active':''}" data-v9-plan="smart">✨ Semana inteligente</button><button class="chip ${planMode==='month'?'active':''}" data-v9-plan="month">🗓️ Plan de 30 días</button></div>`);root.querySelectorAll('[data-v9-plan]').forEach(b=>b.onclick=()=>{planMode=b.dataset.v9Plan;localStorage.setItem('mf_planMode',planMode);enhanceCalendar()});root.querySelectorAll('[data-v9-plan]').forEach(b=>b.classList.toggle('active',b.dataset.v9Plan===planMode));weekly.hidden=planMode!=='smart';if(monthlyTitle)monthlyTitle.hidden=planMode!=='month';if(dayList)dayList.hidden=planMode!=='month';let plan=null;try{plan=JSON.parse(localStorage.getItem('mf_weekPlan')||'null')}catch{}if(!plan)return;root.querySelectorAll('.weekly-planner .week-day').forEach((dayEl,di)=>{dayEl.querySelectorAll('.week-meal').forEach(meal=>{if(meal.querySelector('[data-v9-view-recipe]'))return;const type=meal.querySelector('span')?.textContent?.trim(),id=plan.days?.[di]?.meals?.[type];if(!id)return;const change=meal.querySelector('[data-week-replace]');const btn=document.createElement('button');btn.className='btn small secondary';btn.textContent='Ver receta';btn.dataset.v9ViewRecipe=id;btn.onclick=()=>M.openRecipe?.(id);if(change){let actions=meal.querySelector('.v9-week-actions');if(!actions){actions=document.createElement('div');actions.className='v9-week-actions';change.before(actions);actions.appendChild(change)}actions.prepend(btn)}else meal.appendChild(btn)})})}
const baseCalendar=M.renderers.calendar;M.renderers.calendar=()=>{baseCalendar?.();enhanceCalendar()};

const baseHome=M.renderers.home;M.renderers.home=()=>{baseHome?.();const root=$('#home');if(!root||root.querySelector('.v9-home-shortcuts'))return;const hero=root.querySelector('.hero');hero?.insertAdjacentHTML('afterend',`<div class="v9-home-shortcuts"><button class="v9-shortcut" data-v9-go="calendar"><span>✨</span><b>Plan</b><small>Semana o mes</small></button><button class="v9-shortcut" data-v9-go="recipes"><span>📖</span><b>Recetas</b><small>Buscar y cocinar</small></button><button class="v9-shortcut" data-v9-go="pantry"><span>🥕</span><b>Despensa</b><small>Qué tengo</small></button><button class="v9-shortcut" data-v9-go="shopping"><span>🛒</span><b>Compras</b><small>Qué falta</small></button></div>`);root.querySelectorAll('[data-v9-go]').forEach(b=>b.onclick=()=>M.setTab(b.dataset.v9Go))};

if($('.section.active')?.id==='home')M.renderers.home();
})();
