(()=>{
'use strict';
const M=window.MF;if(!M)return;const {D,$,$$,state,save,norm,esc}=M;
const PLAN_KEY='mf_weekPlan';
const aliases={pollo:['pollo','pechuga','muslo'],res:['res','carne de res','bistec'],cerdo:['cerdo','lomo de cerdo'],pescado:['pescado','tilapia','trucha','atun','atún'],huevo:['huevo'],lenteja:['lenteja'],frijol:['frijol','fríjol'],garbanzo:['garbanzo'],arveja:['arveja'],arroz:['arroz'],papa:['papa'],yuca:['yuca'],platano:['platano','plátano'],arepa:['arepa'],maiz:['maiz','maíz','mazorca'],pasta:['pasta','fideo'],avena:['avena'],quinua:['quinua','quinoa'],pan:['pan'],batata:['batata']};
function canonical(v){const n=norm(v);for(const [k,arr] of Object.entries(aliases))if(arr.some(a=>n===norm(a)||n.includes(norm(a))||norm(a).includes(n)))return k;return n}
function same(a,b){const na=norm(a),nb=norm(b);return !!na&&!!nb&&(na===nb||canonical(na)===canonical(nb)||na.includes(nb)||nb.includes(na))}
function pantry(){return Object.values(state.pantry||{})}
function profile(){return M.familyProfile?.()||{members:[{age:42},{age:38},{age:4}],budget:'medio',weekdayTime:35,weekendTime:60,maxNewIngredients:12,dislikes:'',restrictions:''}}
function scale(){return M.familyScale?.()||1}
function expiryDays(x){if(!x.expiry)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(x.expiry+'T00:00:00');return Math.ceil((b-a)/86400000)}
function exclusions(){const p=profile();return `${p.dislikes||''},${p.restrictions||''}`.split(/[,;\n]+/).map(norm).filter(Boolean)}
function recipeText(r){return norm(`${r.name} ${r.protein} ${r.carb} ${r.produce} ${(r.ingredients||[]).map(i=>i.name).join(' ')}`)}
function allowed(r,maxTime){if(maxTime&&r.time&&Number(r.time)>maxTime)return false;const t=recipeText(r);return !exclusions().some(x=>x&&t.includes(x))}
function proteinFamily(r){return canonical(r.protein||'')}
function costPenalty(r){const p=profile(),f=proteinFamily(r);if(p.budget==='amplio')return 0;if(['res','pescado','cerdo'].includes(f))return p.budget==='economico'?9:3;if(['lenteja','frijol','garbanzo','arveja','huevo'].includes(f))return p.budget==='economico'?-6:-2;return 0}
function ingredientScore(r){const p=pantry(),ings=(r.ingredients||[]).filter(i=>!['Condimentos','Bebidas'].includes(i.category||''));let matched=0,priority=0,missing=0;for(const i of ings){const hit=p.find(x=>same(x.name,i.name));if(hit){matched++;const d=expiryDays(hit);if(hit.priority||d!=null&&d<=3)priority+=2}else missing++}return{matched,priority,missing,coverage:ings.length?matched/ings.length:0}}
function candidates(type,maxTime,used,recentProtein){return D.recipes.filter(r=>r.type===type&&allowed(r,maxTime)&&!used.has(r.id)).map(r=>{const s=ingredientScore(r),pf=proteinFamily(r),repeat=recentProtein&&pf===recentProtein?12:0,libraryBonus=r.day===0?1:0,score=s.coverage*55+s.matched*4+s.priority*8-s.missing*2-costPenalty(r)-repeat+libraryBonus-(Number(r.time)||30)*.08;return{r,score,s,pf}}).sort((a,b)=>b.score-a.score||a.s.missing-b.s.missing||(a.r.time||999)-(b.r.time||999))}
function generate(){const p=profile(),used=new Set(),days=[],last={Desayuno:'',Almuerzo:'',Cena:''};for(let d=0;d<7;d++){const weekend=d>=5,maxTime=weekend?Number(p.weekendTime||60):Number(p.weekdayTime||35),row={date:new Date(Date.now()+d*86400000).toISOString().slice(0,10),meals:{}};for(const type of ['Desayuno','Almuerzo','Cena']){const c=candidates(type,maxTime,used,last[type]);if(!c.length)continue;const pick=c[0];row.meals[type]=pick.r.id;used.add(pick.r.id);last[type]=pick.pf}days.push(row)}const plan={version:1,createdAt:new Date().toISOString(),days,options:{weekdayTime:p.weekdayTime,weekendTime:p.weekendTime,maxNewIngredients:p.maxNewIngredients},shopping:[]};plan.shopping=calcShopping(plan);localStorage.setItem(PLAN_KEY,JSON.stringify(plan));return plan}
function loadPlan(){try{return JSON.parse(localStorage.getItem(PLAN_KEY)||'null')}catch{return null}}
function unitDim(u){u=norm(u);if(['g','kg'].includes(u))return'mass';if(['ml','l'].includes(u))return'volume';if(['unidad','unidades'].includes(u))return'unit';return u||'unknown'}
function toBase(q,u){q=Number(q)||0;u=norm(u);if(u==='kg')return q*1000;if(u==='l')return q*1000;return q}
function prettyQty(q,u){u=norm(u);if(u==='g'&&q>=1000)return{qty:Math.round(q/10)/100,unit:'kg'};if(u==='ml'&&q>=1000)return{qty:Math.round(q/10)/100,unit:'l'};return{qty:Math.round(q*10)/10,unit:u}}
function calcShopping(plan){const req=new Map(),sc=scale();for(const day of plan.days||[])for(const id of Object.values(day.meals||{})){const r=D.recipes.find(x=>x.id===id);if(!r)continue;for(const i of r.ingredients||[]){if(i.qty==null||!i.unit)continue;const key=`${norm(i.name)}|${norm(i.unit)}`,x=req.get(key)||{ingredient:i.name,category:i.category||'Otros',unit:norm(i.unit),qty:0};x.qty+=toBase(Number(i.qty)*sc,i.unit);req.set(key,x)}}const out=[];for(const x of req.values()){const dim=unitDim(x.unit),matches=pantry().filter(p=>same(p.name,x.ingredient)&&unitDim(p.unit)===dim);let unknown=false,have=0;for(const p of matches){if(p.qty===''||p.qty==null){unknown=true;continue}have+=toBase(p.qty,p.unit)}let missing=unknown?0:Math.max(0,x.qty-have);if(missing>0){const y=prettyQty(missing,x.unit);out.push({...x,qty:y.qty,unit:y.unit})}else if(unknown)out.push({...x,qty:0,unit:x.unit,assumed:true})}return out.sort((a,b)=>a.category.localeCompare(b.category,'es')||a.ingredient.localeCompare(b.ingredient,'es'))}
function savePlan(plan){plan.shopping=calcShopping(plan);localStorage.setItem(PLAN_KEY,JSON.stringify(plan));renderCalendar()}
function replace(dayIndex,type){const plan=loadPlan();if(!plan)return;const used=new Set(plan.days.flatMap(d=>Object.values(d.meals||{}))),current=plan.days[dayIndex].meals[type];used.delete(current);const p=profile(),maxTime=dayIndex>=5?Number(p.weekendTime||60):Number(p.weekdayTime||35),prev=dayIndex?D.recipes.find(r=>r.id===plan.days[dayIndex-1].meals[type]):null,c=candidates(type,maxTime,used,proteinFamily(prev||{})).filter(x=>x.r.id!==current);if(c[0]){plan.days[dayIndex].meals[type]=c[0].r.id;savePlan(plan)}}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('es-CO',{weekday:'short',day:'numeric',month:'short'})}
function mealLine(id,di,type){const r=D.recipes.find(x=>x.id===id);if(!r)return'';return `<div class="week-meal"><div><span>${type}</span><b>${esc(r.name)}</b><small>⏱ ${r.time||'—'} min · ${esc(r.protein||'')}</small></div><button class="btn small secondary" data-week-replace="${di}|${type}">Cambiar</button></div>`}
function planHtml(plan){if(!plan)return '<div class="empty compact-empty">Aún no has generado una semana inteligente.</div>';const shopping=plan.shopping||calcShopping(plan),realMissing=shopping.filter(x=>!x.assumed),unknown=shopping.filter(x=>x.assumed);return `<div class="week-summary"><b>${realMissing.length} productos por completar</b><span>${unknown.length?`${unknown.length} ingredientes presentes sin cantidad exacta`:''}</span></div><div class="week-days">${plan.days.map((d,i)=>`<article class="week-day"><h3>${esc(fmtDate(d.date))}</h3>${['Desayuno','Almuerzo','Cena'].map(t=>mealLine(d.meals[t],i,t)).join('')}</article>`).join('')}</div><div class="week-actions"><button class="btn primary" id="weekToShopping">Añadir faltantes a compras</button><button class="btn secondary" id="weekRecalc">Recalcular cantidades</button><button class="btn secondary" id="weekClear">Eliminar semana</button></div>`}
const originalCalendar=M.renderers.calendar;
function renderCalendar(){originalCalendar?.();const root=$('#calendar');if(!root)return;const p=profile(),plan=loadPlan();root.insertAdjacentHTML('afterbegin',`<section class="card weekly-planner"><div class="section-title"><div><h2>🗓️ Planificador inteligente de 7 días</h2><p>Prioriza tu despensa, ingredientes próximos a vencer, tiempo disponible, variedad y presupuesto. Funciona localmente.</p></div></div><div class="planner-options"><label>Entre semana<input id="wpWeekday" class="field" type="number" min="15" max="120" value="${Number(p.weekdayTime)||35}"> min</label><label>Fin de semana<input id="wpWeekend" class="field" type="number" min="15" max="180" value="${Number(p.weekendTime)||60}"> min</label><label>Objetivo máx. compras nuevas<input id="wpMaxNew" class="field" type="number" min="3" max="40" value="${Number(p.maxNewIngredients)||12}"></label><button class="btn primary" id="weekGenerate">${plan?'Regenerar semana':'Generar semana'}</button></div>${planHtml(plan)}<div class="notice">Las cantidades se escalan de forma aproximada según el perfil familiar. Completa cantidades en la despensa para que el descuento de compras sea exacto.</div></section>`);$('#weekGenerate').onclick=()=>{const fp=M.familyProfile?.()||{};fp.weekdayTime=Number($('#wpWeekday').value)||35;fp.weekendTime=Number($('#wpWeekend').value)||60;fp.maxNewIngredients=Number($('#wpMaxNew').value)||12;localStorage.setItem('mf_familyProfile',JSON.stringify(fp));generate();renderCalendar()};$$('[data-week-replace]').forEach(b=>b.onclick=()=>{const [i,t]=b.dataset.weekReplace.split('|');replace(Number(i),t)});$('#weekRecalc')&&($('#weekRecalc').onclick=()=>{const x=loadPlan();if(x)savePlan(x)});$('#weekClear')&&($('#weekClear').onclick=()=>{localStorage.removeItem(PLAN_KEY);renderCalendar()});$('#weekToShopping')&&($('#weekToShopping').onclick=()=>{const x=loadPlan();if(!x)return;(x.shopping||[]).filter(i=>!i.assumed&&i.qty>0).forEach(i=>{const k=norm(i.ingredient);const old=state.extraShopping[k]||{ingredient:i.ingredient,category:'Plan semanal',qty:0,unit:i.unit};if(old.unit===i.unit)old.qty=(Number(old.qty)||0)+Number(i.qty||0);else{old.qty=i.qty;old.unit=i.unit}old.category='Plan semanal';state.extraShopping[k]=old});save();$('#weekToShopping').textContent='Añadidos ✓';$('#weekToShopping').disabled=true})}
M.renderers.calendar=renderCalendar;
const originalShopping=M.renderers.shopping;
M.renderers.shopping=()=>{originalShopping?.();const plan=loadPlan(),root=$('#shopping');if(!plan||!root)return;const real=(plan.shopping||calcShopping(plan)).filter(x=>!x.assumed&&x.qty>0);root.insertAdjacentHTML('beforeend',`<section class="card week-shopping-summary"><h3>🗓️ Semana inteligente</h3><p class="sub">${real.length?`${real.length} productos aún no cubiertos por las cantidades registradas en despensa.`:'La despensa cuantificada cubre los ingredientes de la semana.'}</p>${real.length?`<div class="week-shop-chips">${real.slice(0,20).map(x=>`<span class="mini-chip need">${esc(x.ingredient)} · ${esc(x.qty)} ${esc(x.unit)}</span>`).join('')}</div>`:''}</section>`)};
M.weekPlanner={generate,loadPlan,calcShopping};
})();
